export type MovieType = {
  name: string;
  id: number;
  genres: string;
  department: string;
  site: string;
  Clip: VideoFrameInit;
  official: boolean;
  overview: string;
  title: string;
  original_title: string;
  release_date: number;
  vote_average: number;
  poster_path: boolean;
  backdrop_path: boolean;
  total_pages: number;
  totalPages: number;
  key: string;
  iso_639_1: string;
  iso_3166_1: string;
  published_at: string;
  size: number;
  type: string;
};
